### ISSUE TITLE
EU Ioniq 5 consumption mismatch with car stats.

### ISSUE THREAD

**Issue by teodorch85** [ZuinigeRijder/hyundai_kia_connect_monitor#71]
Hi!
I am using latest version R4.0.3
I fully charged my ioniq 5 on 27/10 in the morning before going for a day trip.
I have attached screenshot from monitor.dailystats and the car's statistics "after recharching" (which was 0 before travelling).

In dailystats I get 14.9kWh/100km and in the car 16.4kWh/100km
I have the following settings. I changed consumption_efficiency_* from 1 to 0.9 to test (after fetching) the first data. I don't know if it recalculates everything or not.

>[monitor]
region = 1
brand = 2
username = xxxxxxxxxxxxxxx
password = xxxxxxxxxxxxxxx
pin = xxxxxxxxxxxxxxxxxx
use_geocode = True
use_geocode_email = True
language = en
odometer_metric = km
include_regenerate_in_consumption = False
consumption_efficiency_factor_dailystats = 0.9
consumption_efficiency_factor_summary = 0.9
monitor_infinite = False
monitor_infinite_interval_minutes = 60
monitor_execute_commands_when_something_written_or_error = 
>

![image](https://github.com/user-attachments/assets/a3bb0e38-b54a-4c2a-8b64-b36ef39c1afd)
![image](https://github.com/user-attachments/assets/f0846d6c-9f52-43d7-96cd-d8765a3dc7a2)

**Comment by teodorch85** [comment]
Reported consumption from car is 16.4kWh/100km which is 39.52kWh for the 241km i travelled. 
Total consumption from dailystats (without removing/adding recuperation) is 35.9kWh 
35.9 +10%*35.9=39.49kwh 
So the car reports ~10% more.
The 
>
consumption_efficiency_factor_dailystats = 0.9
consumption_efficiency_factor_summary = 0.9
>
should work so either it doesn't work, or changing the settings after the first pull of data does not force recalculations.

**Comment by ZuinigeRijder** [comment]
Indeed with the default settings the calculation should be: 100/241 km * 35.9 kWh = 14.896 kWh/100 km
So with setting 0.9 this should have been 14.9 / 0.9 = 16.551 kWh/100 km.

Did you run "python dailystats.py sheetupdate" after the setting change? Because it should recalculate everything.
What is the standard output of the above command showing?

I assume you also did not run monitor.py infinite (the settings say you did not), but if you changed the settings, it will only run dailystats if new data has been ended or once a day.

I am also curious, I see a very high recuperation for your car. More than 54.9%.  My average is 26% over 9600 km, but for longer distance it is often in the order of 10%. Do you have an explanation of why your recuperation is so high?

**Comment by teodorch85** [comment]
I run the command and there was no change. See screenshot. (the version in folder name is not right!)
![image](https://github.com/user-attachments/assets/0e00d45d-7e9a-4b7c-9b71-11837591935b)
 
No I haven't touched the infinite settings yet.

This is the script in Unraid that runs your app every few hours.
![image](https://github.com/user-attachments/assets/e300dd66-5c3b-4299-b262-2c10137f4eaf)

My recuperation is high because 
1) I use i-pedal or AUTO regen and I didn't press the brake more than 5 times for those 240km
2) 180km was on highway and the rest ascending to a mountain and back. So 240-180=60km/2 =~ 30km was mostly regen

**Comment by teodorch85** [comment]
Now I noticed that in total stats I have 55.3% recuperation...
I know that I don't press the brake a lot but I am not sure if this is right.
With my previous car (golf VI tsi 160hp) I changed brake pads front and rear first time at around 100.000-120.000km.
Probably it's the way I drive. I am not a slow drivers, I just let the throttle in time and I don't need to brake a lot!

![image](https://github.com/user-attachments/assets/2dea0e7c-b6af-494a-a0f6-08c53bae0d1b)

**Comment by ZuinigeRijder** [comment]
Thanks for the information. Yeah, Netherlands is a flat country, so descending a mountain will have a lot of recuperation.
I tested with my latest R4.0.3 and that works for me, changing the consumption efficiency. So I am puzzled.

> I run the command and there was no change. See screenshot. (the version in folder name is not right!)
Can you double check/compare the files of your folder with R3.22.0 with the latest R4.0.3? So to be really sure the correct (latest) .py files are in this folder?

**Comment by teodorch85** [comment]
I feel stupid!
I tried to update yesterday but in the process (first time) I was afraid to lose all my stats because I simply copied all files from zip to folder. Then I stopped the copying to backup/rename my .cfg files and I wanted to manually copy only the needed files but for some reason I didn't and I had to leave. Today I tried to continue and I thought that I had updated everything...

I tried to find an update procedure in readme file but there was not and I am a noob :)
Sorry for wasting your time!

**Comment by teodorch85** [comment]
Despite having dailystats.py sheetupdate including a lot of history
![image](https://github.com/user-attachments/assets/64643aef-f5f4-43c2-b038-c62b8c240b0f)

monitor.dailystats includes now only the last 12 days 
![image](https://github.com/user-attachments/assets/5853171c-7982-457f-89d7-2a893d955ce4)

**Comment by ZuinigeRijder** [comment]
> I feel stupid! I tried to update yesterday but in the process (first time) I was afraid to lose all my stats because I simply copied all files from zip to folder. Then I stopped the copying to backup/rename my .cfg files and I wanted to manually copy only the needed files but for some reason I didn't and I had to leave. Today I tried to continue and I thought that I had updated everything...
> 
> I tried to find an update procedure in readme file but there was not and I am a noob :) Sorry for wasting your time!

No worry, the information is overwhelming and probably I write too technical too. One way to have the update procedure:

- (only once) set aside your *.cfg files- copy over all the files from the new release and overwrite existing files
- (optional) check if there are new configuration items in the *.cfg files and adapt your *.cfg files with the new configuration possibilities 
- copy your set aside *.cfg files over the *.cfg of the new release

**Comment by ZuinigeRijder** [comment]
> 
> Now I will start reading the rest of readme to start getting some nice summary stats! Thank you for your app :)

I have an [example monitor.dailystats Google Spreadsheet with some diagrams](https://docs.google.com/spreadsheets/d/1WwdosLQ0ViTHct_kBSNddnd-H3IUc604_Tz-0dgYI9A/edit?usp=sharing), you can copy/save this in Google Spreadsheet with name monitor.dailystats and share this with the client_email (inside service_account.json).

**Comment by ZuinigeRijder** [comment]
> Despite having dailystats.py sheetupdate including a lot of history 
> 
> monitor.dailystats includes now only the last 12 days 

Yeah, the monitor.dailystats spreadsheet only displays the last 122 lines or so. But all data is used in the totals. Note that the standard output of dailystats.py contains all dailystats data retrieved. I did this because there is a limit in the number of rows in the Spreadsheet and you mostly only want to look back the latests days in the spreadsheet.  

> summary sheetupdate also includes some history (not all) 

summary.py only uses the snapshots of the server data, the server has no history for that. So you have to run monitor.py regularly to build up the history in monitor.csv. Therefore also the infinite option has been added, so it is easier to run monitor.py, e.g. every 15 minutes.

> 
> I had data from the end of August
Yeah, probably this is only the dailystats history. I assume the first date of monitor.csv is when you started collection the server snapshots by running monitor.py.
